# Generated by Django 4.2.3 on 2023-08-01 00:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"verbose_name": "포스트", "verbose_name_plural": "포스트들"},
        ),
        migrations.RemoveField(
            model_name="post",
            name="text",
        ),
        migrations.RemoveField(
            model_name="post",
            name="publiShed_date",
        ),
        migrations.AlterField(
            model_name="post",
            name="created_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="작성일"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="posts/", verbose_name="이미지"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="publiShed_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
