# Generated by Django 4.2.3 on 2023-08-03 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bcuser", "0001_initial"),
        ("post", "0002_alter_post_options_remove_post_body_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="text",
            field=models.TextField(null=True, verbose_name="본문"),
        ),
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="bcuser.bcuser",
                verbose_name="작성자",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="작성일"),
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="이미지"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="publiShed_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterModelTable(
            name="comment",
            table="Comment_table",
        ),
        migrations.AlterModelTable(
            name="post",
            table="Post_table",
        ),
    ]
