# Generated by Django 4.2.3 on 2023-07-31 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bcuser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=32, verbose_name="사용자명")),
                ("useremail", models.EmailField(max_length=128, verbose_name="사용자이메일")),
                ("password", models.CharField(max_length=64, verbose_name="비밀번호")),
                (
                    "registered_dttm",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록시간"),
                ),
            ],
            options={
                "verbose_name": "블로그 사용자",
                "verbose_name_plural": "블로그 사용자",
                "db_table": "blog_bcuser",
            },
        ),
    ]
